export const LOCALE_TO_COUNTRY_LANG: Record<string, string> = {
  en: 'EN',
  uk: 'UA',
  ua: 'UA',
  de: 'DE',
  es: 'ES',
  pl: 'PL',
};

export const COUNTRIES = [
  {
    name: 'United States',
    code: '+1',
    flag: '🇺🇸',
    mask: '(###) ###-####',
    lang: 'EN',
    isExtra: true,
  },
  { name: 'Ukraine', code: '+380', flag: '🇺🇦', mask: '(##) ###-##-##', lang: 'UA', isExtra: true },
  { name: 'Germany', code: '+49', flag: '🇩🇪', mask: '### #######', lang: 'DE', isExtra: true },
  { name: 'Spain', code: '+34', flag: '🇪🇸', mask: '### ### ###', lang: 'ES', isExtra: true },
  { name: 'Poland', code: '+48', flag: '🇵🇱', mask: '### ### ###', lang: 'PL', isExtra: true },

  { name: 'Afghanistan', code: '+93', flag: '🇦🇫', mask: '## ### ####' },
  { name: 'Albania', code: '+355', flag: '🇦🇱', mask: '## ### ####' },
  { name: 'Algeria', code: '+213', flag: '🇩🇿', mask: '### ## ## ##' },
  { name: 'Andorra', code: '+376', flag: '🇦🇩', mask: '### ###' },
  { name: 'Angola', code: '+244', flag: '🇦🇴', mask: '### ### ###' },
  { name: 'Antigua and Barbuda', code: '+1', flag: '🇦🇬', mask: '(###) ###-####' },
  { name: 'Argentina', code: '+54', flag: '🇦🇷', mask: '## #### ####' },
  { name: 'Armenia', code: '+374', flag: '🇦🇲', mask: '## ######' },
  { name: 'Australia', code: '+61', flag: '🇦🇺', mask: '### ### ###' },
  { name: 'Austria', code: '+43', flag: '🇦🇹', mask: '### #######' },
  { name: 'Azerbaijan', code: '+994', flag: '🇦🇿', mask: '## ### ## ##' },
  { name: 'Bahamas', code: '+1', flag: '🇧🇸', mask: '(###) ###-####' },
  { name: 'Bahrain', code: '+973', flag: '🇧🇭', mask: '#### ####' },
  { name: 'Bangladesh', code: '+880', flag: '🇧🇩', mask: '#### ### ###' },
  { name: 'Barbados', code: '+1', flag: '🇧🇧', mask: '(###) ###-####' },
  { name: 'Belgium', code: '+32', flag: '🇧🇪', mask: '### ## ## ##' },
  { name: 'Belize', code: '+501', flag: '🇧🇿', mask: '### ####' },
  { name: 'Benin', code: '+229', flag: '🇧🇯', mask: '## ## ## ##' },
  { name: 'Bhutan', code: '+975', flag: '🇧🇹', mask: '## ### ###' },
  { name: 'Bolivia', code: '+591', flag: '🇧🇴', mask: '# ### ####' },
  { name: 'Bosnia and Herzegovina', code: '+387', flag: '🇧🇦', mask: '## ### ###' },
  { name: 'Botswana', code: '+267', flag: '🇧🇼', mask: '## ### ###' },
  { name: 'Brazil', code: '+55', flag: '🇧🇷', mask: '(##) #####-####' },
  { name: 'Brunei', code: '+673', flag: '🇧🇳', mask: '### ####' },
  { name: 'Bulgaria', code: '+359', flag: '🇧🇬', mask: '### ### ###' },
  { name: 'Burkina Faso', code: '+226', flag: '🇧🇫', mask: '## ## ## ##' },
  { name: 'Burundi', code: '+257', flag: '🇧🇮', mask: '## ## ## ##' },
  { name: 'Cambodia', code: '+855', flag: '🇰🇭', mask: '## ### ###' },
  { name: 'Cameroon', code: '+237', flag: '🇨🇲', mask: '#### ####' },
  { name: 'Canada', code: '+1', flag: '🇨🇦', mask: '(###) ###-####' },
  { name: 'Cape Verde', code: '+238', flag: '🇨🇻', mask: '### ## ##' },
  { name: 'Central African Republic', code: '+236', flag: '🇨🇫', mask: '## ## ## ##' },
  { name: 'Chad', code: '+235', flag: '🇹🇩', mask: '## ## ## ##' },
  { name: 'Chile', code: '+56', flag: '🇨🇱', mask: '# #### ####' },
  { name: 'China', code: '+86', flag: '🇨🇳', mask: '### #### ####' },
  { name: 'Colombia', code: '+57', flag: '🇨🇴', mask: '### ### ####' },
  { name: 'Comoros', code: '+269', flag: '🇰🇲', mask: '### ####' },
  { name: 'Congo', code: '+242', flag: '🇨🇬', mask: '## ### ####' },
  { name: 'Costa Rica', code: '+506', flag: '🇨🇷', mask: '#### ####' },
  { name: 'Croatia', code: '+385', flag: '🇭🇷', mask: '## ### ###' },
  { name: 'Cuba', code: '+53', flag: '🇨🇺', mask: '# ### ####' },
  { name: 'Cyprus', code: '+357', flag: '🇨🇾', mask: '## ######' },
  { name: 'Czech Republic', code: '+420', flag: '🇨🇿', mask: '### ### ###' },
  { name: 'Denmark', code: '+45', flag: '🇩🇰', mask: '## ## ## ##' },
  { name: 'Djibouti', code: '+253', flag: '🇩🇯', mask: '## ## ## ##' },
  { name: 'Dominica', code: '+1', flag: '🇩🇲', mask: '(###) ###-####' },
  { name: 'Dominican Republic', code: '+1', flag: '🇩🇴', mask: '(###) ###-####' },
  { name: 'Ecuador', code: '+593', flag: '🇪🇨', mask: '## ### ####' },
  { name: 'Egypt', code: '+20', flag: '🇪🇬', mask: '### ### ####' },
  { name: 'El Salvador', code: '+503', flag: '🇸🇻', mask: '#### ####' },
  { name: 'Equatorial Guinea', code: '+240', flag: '🇬🇶', mask: '### ### ###' },
  { name: 'Eritrea', code: '+291', flag: '🇪🇷', mask: '# ### ###' },
  { name: 'Estonia', code: '+372', flag: '🇪🇪', mask: '#### ####' },
  { name: 'Eswatini', code: '+268', flag: '🇸🇿', mask: '## ## ####' },
  { name: 'Ethiopia', code: '+251', flag: '🇪🇹', mask: '## ### ####' },
  { name: 'Fiji', code: '+679', flag: '🇫🇯', mask: '### ####' },
  { name: 'Finland', code: '+358', flag: '🇫🇮', mask: '### ### ###' },
  { name: 'France', code: '+33', flag: '🇫🇷', mask: '# ## ## ## ##' },
  { name: 'Gabon', code: '+241', flag: '🇬🇦', mask: '# ## ## ##' },
  { name: 'Gambia', code: '+220', flag: '🇬🇲', mask: '### ####' },
  { name: 'Georgia', code: '+995', flag: '🇬🇪', mask: '### ### ###' },
  { name: 'Germany', code: '+49', flag: '🇩🇪', mask: '### #######' },
  { name: 'Ghana', code: '+233', flag: '🇬🇭', mask: '## ### ####' },
  { name: 'Greece', code: '+30', flag: '🇬🇷', mask: '### ### ####' },
  { name: 'Grenada', code: '+1', flag: '🇬🇩', mask: '(###) ###-####' },
  { name: 'Guatemala', code: '+502', flag: '🇬🇹', mask: '#### ####' },
  { name: 'Guinea', code: '+224', flag: '🇬🇳', mask: '### ### ###' },
  { name: 'Guinea-Bissau', code: '+245', flag: '🇬🇼', mask: '### ####' },
  { name: 'Guyana', code: '+592', flag: '🇬🇾', mask: '### ####' },
  { name: 'Haiti', code: '+509', flag: '🇭🇹', mask: '## ## ####' },
  { name: 'Honduras', code: '+504', flag: '🇭🇳', mask: '#### ####' },
  { name: 'Hungary', code: '+36', flag: '🇭🇺', mask: '## ### ####' },
  { name: 'Iceland', code: '+354', flag: '🇮🇸', mask: '### ####' },
  { name: 'India', code: '+91', flag: '🇮🇳', mask: '##### #####' },
  { name: 'Indonesia', code: '+62', flag: '🇮🇩', mask: '### ### ####' },
  { name: 'Iran', code: '+98', flag: '🇮🇷', mask: '### ### ####' },
  { name: 'Iraq', code: '+964', flag: '🇮🇶', mask: '### ### ####' },
  { name: 'Ireland', code: '+353', flag: '🇮🇪', mask: '## ### ####' },
  { name: 'Israel', code: '+972', flag: '🇮🇱', mask: '## ### ####' },
  { name: 'Italy', code: '+39', flag: '🇮🇹', mask: '### #######' },
  { name: 'Jamaica', code: '+1', flag: '🇯🇲', mask: '(###) ###-####' },
  { name: 'Japan', code: '+81', flag: '🇯🇵', mask: '## #### ####' },
  { name: 'Jordan', code: '+962', flag: '🇯🇴', mask: '# #### ####' },
  { name: 'Kazakhstan', code: '+7', flag: '🇰🇿', mask: '(###) ###-##-##' },
  { name: 'Kenya', code: '+254', flag: '🇰🇪', mask: '### ### ###' },
  { name: 'Kiribati', code: '+686', flag: '🇰🇮', mask: '#### ####' },
  { name: 'Kuwait', code: '+965', flag: '🇰🇼', mask: '#### ####' },
  { name: 'Kyrgyzstan', code: '+996', flag: '🇰🇬', mask: '### ### ###' },
  { name: 'Laos', code: '+856', flag: '🇱🇦', mask: '## ### ###' },
  { name: 'Latvia', code: '+371', flag: '🇱🇻', mask: '#### ####' },
  { name: 'Lebanon', code: '+961', flag: '🇱🇧', mask: '## ### ###' },
  { name: 'Lesotho', code: '+266', flag: '🇱🇸', mask: '## ### ###' },
  { name: 'Liberia', code: '+231', flag: '🇱🇷', mask: '## ### ####' },
  { name: 'Libya', code: '+218', flag: '🇱🇾', mask: '## ### ####' },
  { name: 'Liechtenstein', code: '+423', flag: '🇱🇮', mask: '### ## ##' },
  { name: 'Lithuania', code: '+370', flag: '🇱🇹', mask: '### #####' },
  { name: 'Luxembourg', code: '+352', flag: '🇱🇺', mask: '### ### ###' },
  { name: 'Madagascar', code: '+261', flag: '🇲🇬', mask: '## ## ### ##' },
  { name: 'Malawi', code: '+265', flag: '🇲🇼', mask: '### ### ###' },
  { name: 'Malaysia', code: '+60', flag: '🇲🇾', mask: '## ### ####' },
  { name: 'Maldives', code: '+960', flag: '🇲🇻', mask: '### ####' },
  { name: 'Mali', code: '+223', flag: '🇲🇱', mask: '## ## ## ##' },
  { name: 'Malta', code: '+356', flag: '🇲🇹', mask: '#### ####' },
  { name: 'Marshall Islands', code: '+692', flag: '🇲🇭', mask: '### ####' },
  { name: 'Mauritania', code: '+222', flag: '🇲🇷', mask: '## ## ## ##' },
  { name: 'Mauritius', code: '+230', flag: '🇲🇺', mask: '#### ####' },
  { name: 'Mexico', code: '+52', flag: '🇲🇽', mask: '## #### ####' },
  { name: 'Micronesia', code: '+691', flag: '🇫🇲', mask: '### ####' },
  { name: 'Moldova', code: '+373', flag: '🇲🇩', mask: '#### ####' },
  { name: 'Monaco', code: '+377', flag: '🇲🇨', mask: '## ## ## ##' },
  { name: 'Mongolia', code: '+976', flag: '🇲🇳', mask: '## ## ####' },
  { name: 'Montenegro', code: '+382', flag: '🇲🇪', mask: '## ### ###' },
  { name: 'Morocco', code: '+212', flag: '🇲🇦', mask: '### ### ###' },
  { name: 'Mozambique', code: '+258', flag: '🇲🇿', mask: '## ### ####' },
  { name: 'Myanmar', code: '+95', flag: '🇲🇲', mask: '## ### ####' },
  { name: 'Namibia', code: '+264', flag: '🇳🇦', mask: '## ### ####' },
  { name: 'Nauru', code: '+674', flag: '🇳🇷', mask: '### ####' },
  { name: 'Nepal', code: '+977', flag: '🇳🇵', mask: '## #### ####' },
  { name: 'Netherlands', code: '+31', flag: '🇳🇱', mask: '## ########' },
  { name: 'New Zealand', code: '+64', flag: '🇳🇿', mask: '## ### ####' },
  { name: 'Nicaragua', code: '+505', flag: '🇳🇮', mask: '#### ####' },
  { name: 'Niger', code: '+227', flag: '🇳🇪', mask: '## ## ## ##' },
  { name: 'Nigeria', code: '+234', flag: '🇳🇬', mask: '### ### ####' },
  { name: 'North Korea', code: '+850', flag: '🇰🇵', mask: '### ### ####' },
  { name: 'North Macedonia', code: '+389', flag: '🇲🇰', mask: '## ### ###' },
  { name: 'Norway', code: '+47', flag: '🇳🇴', mask: '### ## ###' },
  { name: 'Oman', code: '+968', flag: '🇴🇲', mask: '#### ####' },
  { name: 'Pakistan', code: '+92', flag: '🇵🇰', mask: '### ### ####' },
  { name: 'Palau', code: '+680', flag: '🇵🇼', mask: '### ####' },
  { name: 'Palestine', code: '+970', flag: '🇵🇸', mask: '## ### ####' },
  { name: 'Panama', code: '+507', flag: '🇵🇦', mask: '#### ####' },
  { name: 'Papua New Guinea', code: '+675', flag: '🇵🇬', mask: '### ####' },
  { name: 'Paraguay', code: '+595', flag: '🇵🇾', mask: '### ### ###' },
  { name: 'Peru', code: '+51', flag: '🇵🇪', mask: '### ### ###' },
  { name: 'Philippines', code: '+63', flag: '🇵🇭', mask: '### ### ####' },
  { name: 'Poland', code: '+48', flag: '🇵🇱', mask: '### ### ###' },
  { name: 'Portugal', code: '+351', flag: '🇵🇹', mask: '### ### ###' },
  { name: 'Qatar', code: '+974', flag: '🇶🇦', mask: '#### ####' },
  { name: 'Romania', code: '+40', flag: '🇷🇴', mask: '### ### ###' },
  { name: 'Rwanda', code: '+250', flag: '🇷🇼', mask: '### ### ###' },
  { name: 'Saint Kitts and Nevis', code: '+1', flag: '🇰🇳', mask: '(###) ###-####' },
  { name: 'Saint Lucia', code: '+1', flag: '🇱🇨', mask: '(###) ###-####' },
  { name: 'Saint Vincent and the Grenadines', code: '+1', flag: '🇻🇨', mask: '(###) ###-####' },
  { name: 'Samoa', code: '+685', flag: '🇼🇸', mask: '## ####' },
  { name: 'San Marino', code: '+378', flag: '🇸🇲', mask: '#### ######' },
  { name: 'Sao Tome and Principe', code: '+239', flag: '🇸🇹', mask: '## #####' },
  { name: 'Saudi Arabia', code: '+966', flag: '🇸🇦', mask: '## ### ####' },
  { name: 'Senegal', code: '+221', flag: '🇸🇳', mask: '## ### ## ##' },
  { name: 'Serbia', code: '+381', flag: '🇷🇸', mask: '## ### ####' },
  { name: 'Seychelles', code: '+248', flag: '🇸🇨', mask: '# ### ###' },
  { name: 'Sierra Leone', code: '+232', flag: '🇸🇱', mask: '## ######' },
  { name: 'Singapore', code: '+65', flag: '🇸🇬', mask: '#### ####' },
  { name: 'Slovakia', code: '+421', flag: '🇸🇰', mask: '### ### ###' },
  { name: 'Slovenia', code: '+386', flag: '🇸🇮', mask: '## ### ###' },
  { name: 'Solomon Islands', code: '+677', flag: '🇸🇧', mask: '### ####' },
  { name: 'Somalia', code: '+252', flag: '🇸🇴', mask: '## ### ###' },
  { name: 'South Africa', code: '+27', flag: '🇿🇦', mask: '## ### ####' },
  { name: 'South Korea', code: '+82', flag: '🇰🇷', mask: '## #### ####' },
  { name: 'South Sudan', code: '+211', flag: '🇸🇸', mask: '## ### ####' },
  { name: 'Spain', code: '+34', flag: '🇪🇸', mask: '### ### ###' },
  { name: 'Sri Lanka', code: '+94', flag: '🇱🇰', mask: '## ### ####' },
  { name: 'Sudan', code: '+249', flag: '🇸🇩', mask: '## ### ####' },
  { name: 'Suriname', code: '+597', flag: '🇸🇷', mask: '### ####' },
  { name: 'Sweden', code: '+46', flag: '🇸🇪', mask: '## ### ## ##' },
  { name: 'Switzerland', code: '+41', flag: '🇨🇭', mask: '## ### ## ##' },
  { name: 'Syria', code: '+963', flag: '🇸🇾', mask: '## #### ###' },
  { name: 'Taiwan', code: '+886', flag: '🇹🇼', mask: '### ### ###' },
  { name: 'Tajikistan', code: '+992', flag: '🇹🇯', mask: '## ### ####' },
  { name: 'Tanzania', code: '+255', flag: '🇹🇿', mask: '## ### ####' },
  { name: 'Thailand', code: '+66', flag: '🇹🇭', mask: '## ### ####' },
  { name: 'Timor-Leste', code: '+670', flag: '🇹🇱', mask: '### ####' },
  { name: 'Togo', code: '+228', flag: '🇹🇬', mask: '## ## ## ##' },
  { name: 'Tonga', code: '+676', flag: '🇹🇴', mask: '#####' },
  { name: 'Trinidad and Tobago', code: '+1', flag: '🇹🇹', mask: '(###) ###-####' },
  { name: 'Tunisia', code: '+216', flag: '🇹🇳', mask: '## ### ###' },
  { name: 'Turkey', code: '+90', flag: '🇹🇷', mask: '### ### ## ##' },
  { name: 'Turkmenistan', code: '+993', flag: '🇹🇲', mask: '## ######' },
  { name: 'Tuvalu', code: '+688', flag: '🇹🇻', mask: '#####' },
  { name: 'Uganda', code: '+256', flag: '🇺🇬', mask: '### ### ###' },
  { name: 'Ukraine', code: '+380', flag: '🇺🇦', mask: '(##) ###-##-##' },
  { name: 'United Arab Emirates', code: '+971', flag: '🇦🇪', mask: '# ### ####' },
  { name: 'United Kingdom', code: '+44', flag: '🇬🇧', mask: '## #### ####' },
  { name: 'United States', code: '+1', flag: '🇺🇸', mask: '(###) ###-####' },
  { name: 'Uruguay', code: '+598', flag: '🇺🇾', mask: '## ### ###' },
  { name: 'Uzbekistan', code: '+998', flag: '🇺🇿', mask: '## ### ## ##' },
  { name: 'Vanuatu', code: '+678', flag: '🇻🇺', mask: '## #####' },
  { name: 'Vatican City', code: '+379', flag: '🇻🇦', mask: '######' },
  { name: 'Venezuela', code: '+58', flag: '🇻🇪', mask: '### ### ####' },
  { name: 'Vietnam', code: '+84', flag: '🇻🇳', mask: '## #### ####' },
  { name: 'Yemen', code: '+967', flag: '🇾🇪', mask: '### ### ###' },
  { name: 'Zambia', code: '+260', flag: '🇿🇲', mask: '## ### ####' },
  { name: 'Zimbabwe', code: '+263', flag: '🇿🇼', mask: '## ### ####' },
];
